# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import gymEnv_pb2 as gymEnv__pb2


class GymServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.make = channel.unary_unary(
                '/gymEnv.GymService/make',
                request_serializer=gymEnv__pb2.Msg.SerializeToString,
                response_deserializer=gymEnv__pb2.EnvSpace.FromString,
                )
        self.reset = channel.unary_unary(
                '/gymEnv.GymService/reset',
                request_serializer=gymEnv__pb2.Msg.SerializeToString,
                response_deserializer=gymEnv__pb2.Observation.FromString,
                )
        self.step = channel.unary_unary(
                '/gymEnv.GymService/step',
                request_serializer=gymEnv__pb2.Action.SerializeToString,
                response_deserializer=gymEnv__pb2.StepResult.FromString,
                )
        self.render = channel.unary_unary(
                '/gymEnv.GymService/render',
                request_serializer=gymEnv__pb2.Msg.SerializeToString,
                response_deserializer=gymEnv__pb2.Msg.FromString,
                )
        self.close = channel.unary_unary(
                '/gymEnv.GymService/close',
                request_serializer=gymEnv__pb2.Msg.SerializeToString,
                response_deserializer=gymEnv__pb2.Msg.FromString,
                )


class GymServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def make(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def step(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def render(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def close(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GymServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'make': grpc.unary_unary_rpc_method_handler(
                    servicer.make,
                    request_deserializer=gymEnv__pb2.Msg.FromString,
                    response_serializer=gymEnv__pb2.EnvSpace.SerializeToString,
            ),
            'reset': grpc.unary_unary_rpc_method_handler(
                    servicer.reset,
                    request_deserializer=gymEnv__pb2.Msg.FromString,
                    response_serializer=gymEnv__pb2.Observation.SerializeToString,
            ),
            'step': grpc.unary_unary_rpc_method_handler(
                    servicer.step,
                    request_deserializer=gymEnv__pb2.Action.FromString,
                    response_serializer=gymEnv__pb2.StepResult.SerializeToString,
            ),
            'render': grpc.unary_unary_rpc_method_handler(
                    servicer.render,
                    request_deserializer=gymEnv__pb2.Msg.FromString,
                    response_serializer=gymEnv__pb2.Msg.SerializeToString,
            ),
            'close': grpc.unary_unary_rpc_method_handler(
                    servicer.close,
                    request_deserializer=gymEnv__pb2.Msg.FromString,
                    response_serializer=gymEnv__pb2.Msg.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gymEnv.GymService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GymService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def make(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gymEnv.GymService/make',
            gymEnv__pb2.Msg.SerializeToString,
            gymEnv__pb2.EnvSpace.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gymEnv.GymService/reset',
            gymEnv__pb2.Msg.SerializeToString,
            gymEnv__pb2.Observation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gymEnv.GymService/step',
            gymEnv__pb2.Action.SerializeToString,
            gymEnv__pb2.StepResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def render(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gymEnv.GymService/render',
            gymEnv__pb2.Msg.SerializeToString,
            gymEnv__pb2.Msg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def close(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gymEnv.GymService/close',
            gymEnv__pb2.Msg.SerializeToString,
            gymEnv__pb2.Msg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
